<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Statistik_Penghasilan', 'doctrine');

/**
 * BaseData_Statistik_Penghasilan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $rentang_penghasilan
 * @property integer $jumlah_pendaftar
 * 
 * @method integer                    getId()                  Returns the current record's "id" value
 * @method string                     getRentangPenghasilan()  Returns the current record's "rentang_penghasilan" value
 * @method integer                    getJumlahPendaftar()     Returns the current record's "jumlah_pendaftar" value
 * @method Data_Statistik_Penghasilan setId()                  Sets the current record's "id" value
 * @method Data_Statistik_Penghasilan setRentangPenghasilan()  Sets the current record's "rentang_penghasilan" value
 * @method Data_Statistik_Penghasilan setJumlahPendaftar()     Sets the current record's "jumlah_pendaftar" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Statistik_Penghasilan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Statistik_Penghasilan');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('rentang_penghasilan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('jumlah_pendaftar', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}