<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ranking_Akumulasi', 'doctrine');

/**
 * BaseRanking_Akumulasi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nomor_pendaftaran
 * @property integer $jumlah_siswa_1_5
 * @property float $indeks_mapel_un_1_5
 * @property integer $ranking_mapel_un_1_5
 * @property integer $jumlah_siswa_3_5
 * @property float $indeks_mapel_un_3_5
 * @property integer $ranking_mapel_un_3_5
 * 
 * @method integer           getId()                   Returns the current record's "id" value
 * @method integer           getNomorPendaftaran()     Returns the current record's "nomor_pendaftaran" value
 * @method integer           getJumlahSiswa15()        Returns the current record's "jumlah_siswa_1_5" value
 * @method float             getIndeksMapelUn15()      Returns the current record's "indeks_mapel_un_1_5" value
 * @method integer           getRankingMapelUn15()     Returns the current record's "ranking_mapel_un_1_5" value
 * @method integer           getJumlahSiswa35()        Returns the current record's "jumlah_siswa_3_5" value
 * @method float             getIndeksMapelUn35()      Returns the current record's "indeks_mapel_un_3_5" value
 * @method integer           getRankingMapelUn35()     Returns the current record's "ranking_mapel_un_3_5" value
 * @method Ranking_Akumulasi setId()                   Sets the current record's "id" value
 * @method Ranking_Akumulasi setNomorPendaftaran()     Sets the current record's "nomor_pendaftaran" value
 * @method Ranking_Akumulasi setJumlahSiswa15()        Sets the current record's "jumlah_siswa_1_5" value
 * @method Ranking_Akumulasi setIndeksMapelUn15()      Sets the current record's "indeks_mapel_un_1_5" value
 * @method Ranking_Akumulasi setRankingMapelUn15()     Sets the current record's "ranking_mapel_un_1_5" value
 * @method Ranking_Akumulasi setJumlahSiswa35()        Sets the current record's "jumlah_siswa_3_5" value
 * @method Ranking_Akumulasi setIndeksMapelUn35()      Sets the current record's "indeks_mapel_un_3_5" value
 * @method Ranking_Akumulasi setRankingMapelUn35()     Sets the current record's "ranking_mapel_un_3_5" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRanking_Akumulasi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Ranking_Akumulasi');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nomor_pendaftaran', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('jumlah_siswa_1_5', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('indeks_mapel_un_1_5', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ranking_mapel_un_1_5', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('jumlah_siswa_3_5', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('indeks_mapel_un_3_5', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ranking_mapel_un_3_5', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}