<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Nilai_Status_Tambahan', 'doctrine');

/**
 * BaseData_Nilai_Status_Tambahan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nomor_pendaftaran
 * @property integer $id_status_tambahan
 * @property string $kode_mata_pelajaran
 * @property float $nilai_skala_4
 * @property float $nilai_skala_100
 * @property integer $tahun_kur
 * @property float $kkm
 * 
 * @method integer                    getId()                  Returns the current record's "id" value
 * @method integer                    getNomorPendaftaran()    Returns the current record's "nomor_pendaftaran" value
 * @method integer                    getIdStatusTambahan()    Returns the current record's "id_status_tambahan" value
 * @method string                     getKodeMataPelajaran()   Returns the current record's "kode_mata_pelajaran" value
 * @method float                      getNilaiSkala4()         Returns the current record's "nilai_skala_4" value
 * @method float                      getNilaiSkala100()       Returns the current record's "nilai_skala_100" value
 * @method integer                    getTahunKur()            Returns the current record's "tahun_kur" value
 * @method float                      getKkm()                 Returns the current record's "kkm" value
 * @method Data_Nilai_Status_Tambahan setId()                  Sets the current record's "id" value
 * @method Data_Nilai_Status_Tambahan setNomorPendaftaran()    Sets the current record's "nomor_pendaftaran" value
 * @method Data_Nilai_Status_Tambahan setIdStatusTambahan()    Sets the current record's "id_status_tambahan" value
 * @method Data_Nilai_Status_Tambahan setKodeMataPelajaran()   Sets the current record's "kode_mata_pelajaran" value
 * @method Data_Nilai_Status_Tambahan setNilaiSkala4()         Sets the current record's "nilai_skala_4" value
 * @method Data_Nilai_Status_Tambahan setNilaiSkala100()       Sets the current record's "nilai_skala_100" value
 * @method Data_Nilai_Status_Tambahan setTahunKur()            Sets the current record's "tahun_kur" value
 * @method Data_Nilai_Status_Tambahan setKkm()                 Sets the current record's "kkm" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Nilai_Status_Tambahan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Nilai_Status_Tambahan');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nomor_pendaftaran', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_status_tambahan', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('kode_mata_pelajaran', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nilai_skala_4', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nilai_skala_100', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tahun_kur', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('kkm', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}