<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Karya_Portofolio', 'doctrine');

/**
 * BaseData_Karya_Portofolio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nomor_pendaftaran
 * @property string $id_portofolio
 * @property string $id_karya_portofolio
 * @property string $file_karya
 * @property string $judul_karya
 * 
 * @method integer               getId()                  Returns the current record's "id" value
 * @method string                getNomorPendaftaran()    Returns the current record's "nomor_pendaftaran" value
 * @method string                getIdPortofolio()        Returns the current record's "id_portofolio" value
 * @method string                getIdKaryaPortofolio()   Returns the current record's "id_karya_portofolio" value
 * @method string                getFileKarya()           Returns the current record's "file_karya" value
 * @method string                getJudulKarya()          Returns the current record's "judul_karya" value
 * @method Data_Karya_Portofolio setId()                  Sets the current record's "id" value
 * @method Data_Karya_Portofolio setNomorPendaftaran()    Sets the current record's "nomor_pendaftaran" value
 * @method Data_Karya_Portofolio setIdPortofolio()        Sets the current record's "id_portofolio" value
 * @method Data_Karya_Portofolio setIdKaryaPortofolio()   Sets the current record's "id_karya_portofolio" value
 * @method Data_Karya_Portofolio setFileKarya()           Sets the current record's "file_karya" value
 * @method Data_Karya_Portofolio setJudulKarya()          Sets the current record's "judul_karya" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Karya_Portofolio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Karya_Portofolio');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nomor_pendaftaran', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_portofolio', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_karya_portofolio', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('file_karya', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('judul_karya', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}