<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Pilihan', 'doctrine');

/**
 * BaseData_Pilihan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nomor_pendaftaran
 * @property integer $urutan_ptn
 * @property integer $urutan_program_studi
 * @property integer $kode_program_studi
 * @property string $program_studi
 * 
 * @method integer      getId()                   Returns the current record's "id" value
 * @method integer      getNomorPendaftaran()     Returns the current record's "nomor_pendaftaran" value
 * @method integer      getUrutanPtn()            Returns the current record's "urutan_ptn" value
 * @method integer      getUrutanProgramStudi()   Returns the current record's "urutan_program_studi" value
 * @method integer      getKodeProgramStudi()     Returns the current record's "kode_program_studi" value
 * @method string       getProgramStudi()         Returns the current record's "program_studi" value
 * @method Data_Pilihan setId()                   Sets the current record's "id" value
 * @method Data_Pilihan setNomorPendaftaran()     Sets the current record's "nomor_pendaftaran" value
 * @method Data_Pilihan setUrutanPtn()            Sets the current record's "urutan_ptn" value
 * @method Data_Pilihan setUrutanProgramStudi()   Sets the current record's "urutan_program_studi" value
 * @method Data_Pilihan setKodeProgramStudi()     Sets the current record's "kode_program_studi" value
 * @method Data_Pilihan setProgramStudi()         Sets the current record's "program_studi" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Pilihan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Pilihan');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nomor_pendaftaran', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('urutan_ptn', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('urutan_program_studi', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('kode_program_studi', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('program_studi', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}