<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Kelas_Siswa', 'doctrine');

/**
 * BaseData_Kelas_Siswa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nomor_pendaftaran
 * @property integer $id_kelas
 * 
 * @method integer          getId()                Returns the current record's "id" value
 * @method integer          getNomorPendaftaran()  Returns the current record's "nomor_pendaftaran" value
 * @method integer          getIdKelas()           Returns the current record's "id_kelas" value
 * @method Data_Kelas_Siswa setId()                Sets the current record's "id" value
 * @method Data_Kelas_Siswa setNomorPendaftaran()  Sets the current record's "nomor_pendaftaran" value
 * @method Data_Kelas_Siswa setIdKelas()           Sets the current record's "id_kelas" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Kelas_Siswa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Kelas_Siswa');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nomor_pendaftaran', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_kelas', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}