<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ref_Mata_Pelajaran', 'doctrine');

/**
 * BaseRef_Mata_Pelajaran
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $kode
 * @property string $mata_pelajaran
 * 
 * @method integer            getId()             Returns the current record's "id" value
 * @method string             getKode()           Returns the current record's "kode" value
 * @method string             getMataPelajaran()  Returns the current record's "mata_pelajaran" value
 * @method Ref_Mata_Pelajaran setId()             Sets the current record's "id" value
 * @method Ref_Mata_Pelajaran setKode()           Sets the current record's "kode" value
 * @method Ref_Mata_Pelajaran setMataPelajaran()  Sets the current record's "mata_pelajaran" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRef_Mata_Pelajaran extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Ref_Mata_Pelajaran');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('kode', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('mata_pelajaran', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}