<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Nilai_Mapel_UN_Kolom_SMK_Skala4', 'doctrine');

/**
 * BaseData_Nilai_Mapel_UN_Kolom_SMK_Skala4
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nomor_pendaftaran
 * @property string $kode_jurusan
 * @property string $nama_jurusan
 * @property string $1-ind
 * @property string $1-ind.unit
 * @property string $1-ind.basis
 * @property string $1-mat
 * @property string $1-mat.unit
 * @property string $1-mat.basis
 * @property string $1-ing
 * @property string $1-ing.unit
 * @property string $1-ing.basis
 * @property string $2-ind
 * @property string $2-ind.unit
 * @property string $2-ind.basis
 * @property string $2-mat
 * @property string $2-mat.unit
 * @property string $2-mat.basis
 * @property string $2-ing
 * @property string $2-ing.unit
 * @property string $2-ing.basis
 * @property string $3-ind
 * @property string $3-ind.unit
 * @property string $3-ind.basis
 * @property string $3-mat
 * @property string $3-mat.unit
 * @property string $3-mat.basis
 * @property string $3-ing
 * @property string $3-ing.unit
 * @property string $3-ing.basis
 * @property string $4-ind
 * @property string $4-ind.unit
 * @property string $4-ind.basis
 * @property string $4-mat
 * @property string $4-mat.unit
 * @property string $4-mat.basis
 * @property string $4-ing
 * @property string $4-ing.unit
 * @property string $4-ing.basis
 * @property string $5-ind
 * @property string $5-ind.unit
 * @property string $5-ind.basis
 * @property string $5-mat
 * @property string $5-mat.unit
 * @property string $5-mat.basis
 * @property string $5-ing
 * @property string $5-ing.unit
 * @property string $5-ing.basis
 * @property string $6
 * 
 * @method integer                              getId()                Returns the current record's "id" value
 * @method string                               getNomorPendaftaran()  Returns the current record's "nomor_pendaftaran" value
 * @method string                               getKodeJurusan()       Returns the current record's "kode_jurusan" value
 * @method string                               getNamaJurusan()       Returns the current record's "nama_jurusan" value
 * @method string                               get1()                 Returns the current record's "1" value
 * @method string                               get2()                 Returns the current record's "2" value
 * @method string                               get3()                 Returns the current record's "3" value
 * @method string                               get4()                 Returns the current record's "4" value
 * @method string                               get5()                 Returns the current record's "5" value
 * @method string                               get6()                 Returns the current record's "6" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setId()                Sets the current record's "id" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNomorPendaftaran()  Sets the current record's "nomor_pendaftaran" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setKodeJurusan()       Sets the current record's "kode_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNamaJurusan()       Sets the current record's "nama_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set1()                 Sets the current record's "1" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set2()                 Sets the current record's "2" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set3()                 Sets the current record's "3" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set4()                 Sets the current record's "4" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set5()                 Sets the current record's "5" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set6()                 Sets the current record's "6" value-ind
 * @property string $6
 * 
 * @method integer                              getId()                Returns the current record's "id" value
 * @method string                               getNomorPendaftaran()  Returns the current record's "nomor_pendaftaran" value
 * @method string                               getKodeJurusan()       Returns the current record's "kode_jurusan" value
 * @method string                               getNamaJurusan()       Returns the current record's "nama_jurusan" value
 * @method string                               get1()                 Returns the current record's "1" value
 * @method string                               get2()                 Returns the current record's "2" value
 * @method string                               get3()                 Returns the current record's "3" value
 * @method string                               get4()                 Returns the current record's "4" value
 * @method string                               get5()                 Returns the current record's "5" value
 * @method string                               get6()                 Returns the current record's "6" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setId()                Sets the current record's "id" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNomorPendaftaran()  Sets the current record's "nomor_pendaftaran" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setKodeJurusan()       Sets the current record's "kode_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNamaJurusan()       Sets the current record's "nama_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set1()                 Sets the current record's "1" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set2()                 Sets the current record's "2" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set3()                 Sets the current record's "3" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set4()                 Sets the current record's "4" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set5()                 Sets the current record's "5" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set6()                 Sets the current record's "6" value-ind.unit
 * @property string $6
 * 
 * @method integer                              getId()                Returns the current record's "id" value
 * @method string                               getNomorPendaftaran()  Returns the current record's "nomor_pendaftaran" value
 * @method string                               getKodeJurusan()       Returns the current record's "kode_jurusan" value
 * @method string                               getNamaJurusan()       Returns the current record's "nama_jurusan" value
 * @method string                               get1()                 Returns the current record's "1" value
 * @method string                               get2()                 Returns the current record's "2" value
 * @method string                               get3()                 Returns the current record's "3" value
 * @method string                               get4()                 Returns the current record's "4" value
 * @method string                               get5()                 Returns the current record's "5" value
 * @method string                               get6()                 Returns the current record's "6" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setId()                Sets the current record's "id" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNomorPendaftaran()  Sets the current record's "nomor_pendaftaran" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setKodeJurusan()       Sets the current record's "kode_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNamaJurusan()       Sets the current record's "nama_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set1()                 Sets the current record's "1" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set2()                 Sets the current record's "2" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set3()                 Sets the current record's "3" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set4()                 Sets the current record's "4" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set5()                 Sets the current record's "5" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set6()                 Sets the current record's "6" value-ind.basis
 * @property string $6
 * 
 * @method integer                              getId()                Returns the current record's "id" value
 * @method string                               getNomorPendaftaran()  Returns the current record's "nomor_pendaftaran" value
 * @method string                               getKodeJurusan()       Returns the current record's "kode_jurusan" value
 * @method string                               getNamaJurusan()       Returns the current record's "nama_jurusan" value
 * @method string                               get1()                 Returns the current record's "1" value
 * @method string                               get2()                 Returns the current record's "2" value
 * @method string                               get3()                 Returns the current record's "3" value
 * @method string                               get4()                 Returns the current record's "4" value
 * @method string                               get5()                 Returns the current record's "5" value
 * @method string                               get6()                 Returns the current record's "6" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setId()                Sets the current record's "id" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNomorPendaftaran()  Sets the current record's "nomor_pendaftaran" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setKodeJurusan()       Sets the current record's "kode_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNamaJurusan()       Sets the current record's "nama_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set1()                 Sets the current record's "1" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set2()                 Sets the current record's "2" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set3()                 Sets the current record's "3" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set4()                 Sets the current record's "4" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set5()                 Sets the current record's "5" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set6()                 Sets the current record's "6" value-mat
 * @property string $6
 * 
 * @method integer                              getId()                Returns the current record's "id" value
 * @method string                               getNomorPendaftaran()  Returns the current record's "nomor_pendaftaran" value
 * @method string                               getKodeJurusan()       Returns the current record's "kode_jurusan" value
 * @method string                               getNamaJurusan()       Returns the current record's "nama_jurusan" value
 * @method string                               get1()                 Returns the current record's "1" value
 * @method string                               get2()                 Returns the current record's "2" value
 * @method string                               get3()                 Returns the current record's "3" value
 * @method string                               get4()                 Returns the current record's "4" value
 * @method string                               get5()                 Returns the current record's "5" value
 * @method string                               get6()                 Returns the current record's "6" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setId()                Sets the current record's "id" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNomorPendaftaran()  Sets the current record's "nomor_pendaftaran" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setKodeJurusan()       Sets the current record's "kode_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNamaJurusan()       Sets the current record's "nama_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set1()                 Sets the current record's "1" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set2()                 Sets the current record's "2" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set3()                 Sets the current record's "3" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set4()                 Sets the current record's "4" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set5()                 Sets the current record's "5" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set6()                 Sets the current record's "6" value-mat.unit
 * @property string $6
 * 
 * @method integer                              getId()                Returns the current record's "id" value
 * @method string                               getNomorPendaftaran()  Returns the current record's "nomor_pendaftaran" value
 * @method string                               getKodeJurusan()       Returns the current record's "kode_jurusan" value
 * @method string                               getNamaJurusan()       Returns the current record's "nama_jurusan" value
 * @method string                               get1()                 Returns the current record's "1" value
 * @method string                               get2()                 Returns the current record's "2" value
 * @method string                               get3()                 Returns the current record's "3" value
 * @method string                               get4()                 Returns the current record's "4" value
 * @method string                               get5()                 Returns the current record's "5" value
 * @method string                               get6()                 Returns the current record's "6" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setId()                Sets the current record's "id" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNomorPendaftaran()  Sets the current record's "nomor_pendaftaran" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setKodeJurusan()       Sets the current record's "kode_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNamaJurusan()       Sets the current record's "nama_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set1()                 Sets the current record's "1" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set2()                 Sets the current record's "2" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set3()                 Sets the current record's "3" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set4()                 Sets the current record's "4" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set5()                 Sets the current record's "5" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set6()                 Sets the current record's "6" value-mat.basis
 * @property string $6
 * 
 * @method integer                              getId()                Returns the current record's "id" value
 * @method string                               getNomorPendaftaran()  Returns the current record's "nomor_pendaftaran" value
 * @method string                               getKodeJurusan()       Returns the current record's "kode_jurusan" value
 * @method string                               getNamaJurusan()       Returns the current record's "nama_jurusan" value
 * @method string                               get1()                 Returns the current record's "1" value
 * @method string                               get2()                 Returns the current record's "2" value
 * @method string                               get3()                 Returns the current record's "3" value
 * @method string                               get4()                 Returns the current record's "4" value
 * @method string                               get5()                 Returns the current record's "5" value
 * @method string                               get6()                 Returns the current record's "6" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setId()                Sets the current record's "id" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNomorPendaftaran()  Sets the current record's "nomor_pendaftaran" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setKodeJurusan()       Sets the current record's "kode_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNamaJurusan()       Sets the current record's "nama_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set1()                 Sets the current record's "1" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set2()                 Sets the current record's "2" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set3()                 Sets the current record's "3" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set4()                 Sets the current record's "4" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set5()                 Sets the current record's "5" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set6()                 Sets the current record's "6" value-ing
 * @property string $6
 * 
 * @method integer                              getId()                Returns the current record's "id" value
 * @method string                               getNomorPendaftaran()  Returns the current record's "nomor_pendaftaran" value
 * @method string                               getKodeJurusan()       Returns the current record's "kode_jurusan" value
 * @method string                               getNamaJurusan()       Returns the current record's "nama_jurusan" value
 * @method string                               get1()                 Returns the current record's "1" value
 * @method string                               get2()                 Returns the current record's "2" value
 * @method string                               get3()                 Returns the current record's "3" value
 * @method string                               get4()                 Returns the current record's "4" value
 * @method string                               get5()                 Returns the current record's "5" value
 * @method string                               get6()                 Returns the current record's "6" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setId()                Sets the current record's "id" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNomorPendaftaran()  Sets the current record's "nomor_pendaftaran" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setKodeJurusan()       Sets the current record's "kode_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNamaJurusan()       Sets the current record's "nama_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set1()                 Sets the current record's "1" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set2()                 Sets the current record's "2" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set3()                 Sets the current record's "3" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set4()                 Sets the current record's "4" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set5()                 Sets the current record's "5" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set6()                 Sets the current record's "6" value-ing.unit
 * @property string $6
 * 
 * @method integer                              getId()                Returns the current record's "id" value
 * @method string                               getNomorPendaftaran()  Returns the current record's "nomor_pendaftaran" value
 * @method string                               getKodeJurusan()       Returns the current record's "kode_jurusan" value
 * @method string                               getNamaJurusan()       Returns the current record's "nama_jurusan" value
 * @method string                               get1()                 Returns the current record's "1" value
 * @method string                               get2()                 Returns the current record's "2" value
 * @method string                               get3()                 Returns the current record's "3" value
 * @method string                               get4()                 Returns the current record's "4" value
 * @method string                               get5()                 Returns the current record's "5" value
 * @method string                               get6()                 Returns the current record's "6" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setId()                Sets the current record's "id" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNomorPendaftaran()  Sets the current record's "nomor_pendaftaran" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setKodeJurusan()       Sets the current record's "kode_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 setNamaJurusan()       Sets the current record's "nama_jurusan" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set1()                 Sets the current record's "1" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set2()                 Sets the current record's "2" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set3()                 Sets the current record's "3" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set4()                 Sets the current record's "4" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set5()                 Sets the current record's "5" value
 * @method Data_Nilai_Mapel_UN_Kolom_SMK_Skala4 set6()                 Sets the current record's "6" value-ing.basis
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Nilai_Mapel_UN_Kolom_SMK_Skala4 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Nilai_Mapel_UN_Kolom_SMK_Skala4');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nomor_pendaftaran', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('kode_jurusan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nama_jurusan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('1-ind', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('1-ind.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('1-ind.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('1-mat', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('1-mat.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('1-mat.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('1-ing', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('1-ing.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('1-ing.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('2-ind', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('2-ind.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('2-ind.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('2-mat', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('2-mat.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('2-mat.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('2-ing', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('2-ing.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('2-ing.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('3-ind', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('3-ind.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('3-ind.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('3-mat', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('3-mat.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('3-mat.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('3-ing', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('3-ing.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('3-ing.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('4-ind', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('4-ind.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('4-ind.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('4-mat', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('4-mat.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('4-mat.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('4-ing', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('4-ing.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('4-ing.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('5-ind', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('5-ind.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('5-ind.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('5-mat', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('5-mat.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('5-mat.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('5-ing', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('5-ing.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('5-ing.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('6-ind', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('6-ind.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('6-ind.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('6-mat', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('6-mat.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('6-mat.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('6-ing', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('6-ing.unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('6-ing.basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}