<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ref_Jenis_Portofolio', 'doctrine');

/**
 * BaseRef_Jenis_Portofolio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $kode_jenis_portofolio
 * @property string $jenis_portofolio
 * 
 * @method integer              getId()                    Returns the current record's "id" value
 * @method string               getKodeJenisPortofolio()   Returns the current record's "kode_jenis_portofolio" value
 * @method string               getJenisPortofolio()       Returns the current record's "jenis_portofolio" value
 * @method Ref_Jenis_Portofolio setId()                    Sets the current record's "id" value
 * @method Ref_Jenis_Portofolio setKodeJenisPortofolio()   Sets the current record's "kode_jenis_portofolio" value
 * @method Ref_Jenis_Portofolio setJenisPortofolio()       Sets the current record's "jenis_portofolio" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRef_Jenis_Portofolio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Ref_Jenis_Portofolio');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('kode_jenis_portofolio', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('jenis_portofolio', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}