<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Jurusan', 'doctrine');

/**
 * BaseData_Jurusan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_jurusan
 * @property integer $npsn_sekolah
 * @property integer $masa_studi_dalam_tahun
 * @property string $kode_jurusan
 * @property string $akreditasi
 * @property string $nilai_akreditasi
 * @property string $file_akreditasi
 * 
 * @method integer      getId()                     Returns the current record's "id" value
 * @method integer      getIdJurusan()              Returns the current record's "id_jurusan" value
 * @method integer      getNpsnSekolah()            Returns the current record's "npsn_sekolah" value
 * @method integer      getMasaStudiDalamTahun()    Returns the current record's "masa_studi_dalam_tahun" value
 * @method string       getKodeJurusan()            Returns the current record's "kode_jurusan" value
 * @method string       getAkreditasi()             Returns the current record's "akreditasi" value
 * @method string       getNilaiAkreditasi()        Returns the current record's "nilai_akreditasi" value
 * @method string       getFileAkreditasi()         Returns the current record's "file_akreditasi" value
 * @method Data_Jurusan setId()                     Sets the current record's "id" value
 * @method Data_Jurusan setIdJurusan()              Sets the current record's "id_jurusan" value
 * @method Data_Jurusan setNpsnSekolah()            Sets the current record's "npsn_sekolah" value
 * @method Data_Jurusan setMasaStudiDalamTahun()    Sets the current record's "masa_studi_dalam_tahun" value
 * @method Data_Jurusan setKodeJurusan()            Sets the current record's "kode_jurusan" value
 * @method Data_Jurusan setAkreditasi()             Sets the current record's "akreditasi" value
 * @method Data_Jurusan setNilaiAkreditasi()        Sets the current record's "nilai_akreditasi" value
 * @method Data_Jurusan setFileAkreditasi()         Sets the current record's "file_akreditasi" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Jurusan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Jurusan');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_jurusan', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('npsn_sekolah', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('masa_studi_dalam_tahun', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('kode_jurusan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('akreditasi', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nilai_akreditasi', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('file_akreditasi', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}