<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Prestasi', 'doctrine');

/**
 * BaseData_Prestasi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nomor_pendaftaran
 * @property integer $id_prestasi
 * @property string $jenis_prestasi
 * @property string $jenjang_prestasi
 * @property string $file_sertifikat
 * 
 * @method integer       getId()                Returns the current record's "id" value
 * @method integer       getNomorPendaftaran()  Returns the current record's "nomor_pendaftaran" value
 * @method integer       getIdPrestasi()        Returns the current record's "id_prestasi" value
 * @method string        getJenisPrestasi()     Returns the current record's "jenis_prestasi" value
 * @method string        getJenjangPrestasi()   Returns the current record's "jenjang_prestasi" value
 * @method string        getFileSertifikat()    Returns the current record's "file_sertifikat" value
 * @method Data_Prestasi setId()                Sets the current record's "id" value
 * @method Data_Prestasi setNomorPendaftaran()  Sets the current record's "nomor_pendaftaran" value
 * @method Data_Prestasi setIdPrestasi()        Sets the current record's "id_prestasi" value
 * @method Data_Prestasi setJenisPrestasi()     Sets the current record's "jenis_prestasi" value
 * @method Data_Prestasi setJenjangPrestasi()   Sets the current record's "jenjang_prestasi" value
 * @method Data_Prestasi setFileSertifikat()    Sets the current record's "file_sertifikat" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Prestasi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Prestasi');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nomor_pendaftaran', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_prestasi', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('jenis_prestasi', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('jenjang_prestasi', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('file_sertifikat', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}