<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ref_Mata_Pelajaran_Jurusan', 'doctrine');

/**
 * BaseRef_Mata_Pelajaran_Jurusan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $kode_jurusan
 * @property string $kode_mata_pelajaran
 * @property boolean $diujikan_dalam_un
 * 
 * @method integer                    getId()                  Returns the current record's "id" value
 * @method string                     getKodeJurusan()         Returns the current record's "kode_jurusan" value
 * @method string                     getKodeMataPelajaran()   Returns the current record's "kode_mata_pelajaran" value
 * @method boolean                    getDiujikanDalamUn()     Returns the current record's "diujikan_dalam_un" value
 * @method Ref_Mata_Pelajaran_Jurusan setId()                  Sets the current record's "id" value
 * @method Ref_Mata_Pelajaran_Jurusan setKodeJurusan()         Sets the current record's "kode_jurusan" value
 * @method Ref_Mata_Pelajaran_Jurusan setKodeMataPelajaran()   Sets the current record's "kode_mata_pelajaran" value
 * @method Ref_Mata_Pelajaran_Jurusan setDiujikanDalamUn()     Sets the current record's "diujikan_dalam_un" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRef_Mata_Pelajaran_Jurusan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Ref_Mata_Pelajaran_Jurusan');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('kode_jurusan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('kode_mata_pelajaran', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('diujikan_dalam_un', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}