<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Siswa', 'doctrine');

/**
 * BaseData_Siswa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nomor_pendaftaran
 * @property string $nama_siswa
 * @property string $file_foto
 * @property integer $id_jurusan
 * @property integer $npsn_sekolah
 * @property string $kode_jenis_kelamin
 * @property string $tanggal_lahir
 * @property integer $nis
 * @property integer $nisn
 * @property integer $nik
 * @property float $nomor_un
 * @property float $tahun_un
 * @property string $bidikmisi
 * @property float $kap_bidik_misi
 * @property integer $jumlah_nilai_dibawah_kkm
 * @property string $kode_jenis_kelas
 * @property integer $tidak_naik_kelas
 * @property integer $siswa_pindahan
 * @property integer $siswa_pertukaran_pelajar
 * @property integer $siswa_cuti
 * 
 * @method integer    getId()                       Returns the current record's "id" value
 * @method integer    getNomorPendaftaran()         Returns the current record's "nomor_pendaftaran" value
 * @method string     getNamaSiswa()                Returns the current record's "nama_siswa" value
 * @method string     getFileFoto()                 Returns the current record's "file_foto" value
 * @method integer    getIdJurusan()                Returns the current record's "id_jurusan" value
 * @method integer    getNpsnSekolah()              Returns the current record's "npsn_sekolah" value
 * @method string     getKodeJenisKelamin()         Returns the current record's "kode_jenis_kelamin" value
 * @method string     getTanggalLahir()             Returns the current record's "tanggal_lahir" value
 * @method integer    getNis()                      Returns the current record's "nis" value
 * @method integer    getNisn()                     Returns the current record's "nisn" value
 * @method integer    getNik()                      Returns the current record's "nik" value
 * @method float      getNomorUn()                  Returns the current record's "nomor_un" value
 * @method float      getTahunUn()                  Returns the current record's "tahun_un" value
 * @method string     getBidikmisi()                Returns the current record's "bidikmisi" value
 * @method float      getKapBidikMisi()             Returns the current record's "kap_bidik_misi" value
 * @method integer    getJumlahNilaiDibawahKkm()    Returns the current record's "jumlah_nilai_dibawah_kkm" value
 * @method string     getKodeJenisKelas()           Returns the current record's "kode_jenis_kelas" value
 * @method integer    getTidakNaikKelas()           Returns the current record's "tidak_naik_kelas" value
 * @method integer    getSiswaPindahan()            Returns the current record's "siswa_pindahan" value
 * @method integer    getSiswaPertukaranPelajar()   Returns the current record's "siswa_pertukaran_pelajar" value
 * @method integer    getSiswaCuti()                Returns the current record's "siswa_cuti" value
 * @method Data_Siswa setId()                       Sets the current record's "id" value
 * @method Data_Siswa setNomorPendaftaran()         Sets the current record's "nomor_pendaftaran" value
 * @method Data_Siswa setNamaSiswa()                Sets the current record's "nama_siswa" value
 * @method Data_Siswa setFileFoto()                 Sets the current record's "file_foto" value
 * @method Data_Siswa setIdJurusan()                Sets the current record's "id_jurusan" value
 * @method Data_Siswa setNpsnSekolah()              Sets the current record's "npsn_sekolah" value
 * @method Data_Siswa setKodeJenisKelamin()         Sets the current record's "kode_jenis_kelamin" value
 * @method Data_Siswa setTanggalLahir()             Sets the current record's "tanggal_lahir" value
 * @method Data_Siswa setNis()                      Sets the current record's "nis" value
 * @method Data_Siswa setNisn()                     Sets the current record's "nisn" value
 * @method Data_Siswa setNik()                      Sets the current record's "nik" value
 * @method Data_Siswa setNomorUn()                  Sets the current record's "nomor_un" value
 * @method Data_Siswa setTahunUn()                  Sets the current record's "tahun_un" value
 * @method Data_Siswa setBidikmisi()                Sets the current record's "bidikmisi" value
 * @method Data_Siswa setKapBidikMisi()             Sets the current record's "kap_bidik_misi" value
 * @method Data_Siswa setJumlahNilaiDibawahKkm()    Sets the current record's "jumlah_nilai_dibawah_kkm" value
 * @method Data_Siswa setKodeJenisKelas()           Sets the current record's "kode_jenis_kelas" value
 * @method Data_Siswa setTidakNaikKelas()           Sets the current record's "tidak_naik_kelas" value
 * @method Data_Siswa setSiswaPindahan()            Sets the current record's "siswa_pindahan" value
 * @method Data_Siswa setSiswaPertukaranPelajar()   Sets the current record's "siswa_pertukaran_pelajar" value
 * @method Data_Siswa setSiswaCuti()                Sets the current record's "siswa_cuti" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Siswa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Siswa');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nomor_pendaftaran', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('nama_siswa', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('file_foto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_jurusan', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('npsn_sekolah', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('kode_jenis_kelamin', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tanggal_lahir', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nis', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('nisn', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('nik', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('nomor_un', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tahun_un', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('bidikmisi', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('kap_bidik_misi', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('jumlah_nilai_dibawah_kkm', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('kode_jenis_kelas', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tidak_naik_kelas', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('siswa_pindahan', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('siswa_pertukaran_pelajar', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('siswa_cuti', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}