<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ref_Jenis_Kelamin', 'doctrine');

/**
 * BaseRef_Jenis_Kelamin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $kode
 * @property string $jenis_kelamin
 * 
 * @method integer           getId()            Returns the current record's "id" value
 * @method string            getKode()          Returns the current record's "kode" value
 * @method string            getJenisKelamin()  Returns the current record's "jenis_kelamin" value
 * @method Ref_Jenis_Kelamin setId()            Sets the current record's "id" value
 * @method Ref_Jenis_Kelamin setKode()          Sets the current record's "kode" value
 * @method Ref_Jenis_Kelamin setJenisKelamin()  Sets the current record's "jenis_kelamin" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRef_Jenis_Kelamin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Ref_Jenis_Kelamin');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('kode', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('jenis_kelamin', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}