<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Status_Tambahan', 'doctrine');

/**
 * BaseData_Status_Tambahan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nomor_pendaftaran
 * @property integer $id_status_tambahan
 * @property string $kode_status_tambahan
 * @property integer $tahun_ajaran
 * @property integer $tingkat
 * @property integer $semester
 * @property string $kode_jurusan
 * @property string $nama_kelas
 * @property float $npsn_sekolah
 * @property string $nama_sekolah
 * @property integer $nisn_siswa
 * 
 * @method integer              getId()                   Returns the current record's "id" value
 * @method integer              getNomorPendaftaran()     Returns the current record's "nomor_pendaftaran" value
 * @method integer              getIdStatusTambahan()     Returns the current record's "id_status_tambahan" value
 * @method string               getKodeStatusTambahan()   Returns the current record's "kode_status_tambahan" value
 * @method integer              getTahunAjaran()          Returns the current record's "tahun_ajaran" value
 * @method integer              getTingkat()              Returns the current record's "tingkat" value
 * @method integer              getSemester()             Returns the current record's "semester" value
 * @method string               getKodeJurusan()          Returns the current record's "kode_jurusan" value
 * @method string               getNamaKelas()            Returns the current record's "nama_kelas" value
 * @method float                getNpsnSekolah()          Returns the current record's "npsn_sekolah" value
 * @method string               getNamaSekolah()          Returns the current record's "nama_sekolah" value
 * @method integer              getNisnSiswa()            Returns the current record's "nisn_siswa" value
 * @method Data_Status_Tambahan setId()                   Sets the current record's "id" value
 * @method Data_Status_Tambahan setNomorPendaftaran()     Sets the current record's "nomor_pendaftaran" value
 * @method Data_Status_Tambahan setIdStatusTambahan()     Sets the current record's "id_status_tambahan" value
 * @method Data_Status_Tambahan setKodeStatusTambahan()   Sets the current record's "kode_status_tambahan" value
 * @method Data_Status_Tambahan setTahunAjaran()          Sets the current record's "tahun_ajaran" value
 * @method Data_Status_Tambahan setTingkat()              Sets the current record's "tingkat" value
 * @method Data_Status_Tambahan setSemester()             Sets the current record's "semester" value
 * @method Data_Status_Tambahan setKodeJurusan()          Sets the current record's "kode_jurusan" value
 * @method Data_Status_Tambahan setNamaKelas()            Sets the current record's "nama_kelas" value
 * @method Data_Status_Tambahan setNpsnSekolah()          Sets the current record's "npsn_sekolah" value
 * @method Data_Status_Tambahan setNamaSekolah()          Sets the current record's "nama_sekolah" value
 * @method Data_Status_Tambahan setNisnSiswa()            Sets the current record's "nisn_siswa" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Status_Tambahan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Status_Tambahan');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nomor_pendaftaran', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_status_tambahan', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('kode_status_tambahan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tahun_ajaran', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('tingkat', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('semester', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('kode_jurusan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nama_kelas', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('npsn_sekolah', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nama_sekolah', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nisn_siswa', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}