<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Sekolah', 'doctrine');

/**
 * BaseData_Sekolah
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $npsn
 * @property string $id_sekolah_pdsp
 * @property string $nama_sekolah
 * @property string $jenis_sekolah
 * @property integer $kode_kabupaten
 * @property string $nama_kabupaten
 * @property integer $kode_propinsi
 * @property string $nama_propinsi
 * @property string $akreditasi_sekolah
 * @property string $nilai_akreditasi
 * @property float $file_akreditasi
 * @property string $tanggal_kadaluarsa
 * @property string $kepemilikan
 * 
 * @method integer      getId()                 Returns the current record's "id" value
 * @method integer      getNpsn()               Returns the current record's "npsn" value
 * @method string       getIdSekolahPdsp()      Returns the current record's "id_sekolah_pdsp" value
 * @method string       getNamaSekolah()        Returns the current record's "nama_sekolah" value
 * @method string       getJenisSekolah()       Returns the current record's "jenis_sekolah" value
 * @method integer      getKodeKabupaten()      Returns the current record's "kode_kabupaten" value
 * @method string       getNamaKabupaten()      Returns the current record's "nama_kabupaten" value
 * @method integer      getKodePropinsi()       Returns the current record's "kode_propinsi" value
 * @method string       getNamaPropinsi()       Returns the current record's "nama_propinsi" value
 * @method string       getAkreditasiSekolah()  Returns the current record's "akreditasi_sekolah" value
 * @method string       getNilaiAkreditasi()    Returns the current record's "nilai_akreditasi" value
 * @method float        getFileAkreditasi()     Returns the current record's "file_akreditasi" value
 * @method string       getTanggalKadaluarsa()  Returns the current record's "tanggal_kadaluarsa" value
 * @method string       getKepemilikan()        Returns the current record's "kepemilikan" value
 * @method Data_Sekolah setId()                 Sets the current record's "id" value
 * @method Data_Sekolah setNpsn()               Sets the current record's "npsn" value
 * @method Data_Sekolah setIdSekolahPdsp()      Sets the current record's "id_sekolah_pdsp" value
 * @method Data_Sekolah setNamaSekolah()        Sets the current record's "nama_sekolah" value
 * @method Data_Sekolah setJenisSekolah()       Sets the current record's "jenis_sekolah" value
 * @method Data_Sekolah setKodeKabupaten()      Sets the current record's "kode_kabupaten" value
 * @method Data_Sekolah setNamaKabupaten()      Sets the current record's "nama_kabupaten" value
 * @method Data_Sekolah setKodePropinsi()       Sets the current record's "kode_propinsi" value
 * @method Data_Sekolah setNamaPropinsi()       Sets the current record's "nama_propinsi" value
 * @method Data_Sekolah setAkreditasiSekolah()  Sets the current record's "akreditasi_sekolah" value
 * @method Data_Sekolah setNilaiAkreditasi()    Sets the current record's "nilai_akreditasi" value
 * @method Data_Sekolah setFileAkreditasi()     Sets the current record's "file_akreditasi" value
 * @method Data_Sekolah setTanggalKadaluarsa()  Sets the current record's "tanggal_kadaluarsa" value
 * @method Data_Sekolah setKepemilikan()        Sets the current record's "kepemilikan" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Sekolah extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Sekolah');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('npsn', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_sekolah_pdsp', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nama_sekolah', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('jenis_sekolah', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('kode_kabupaten', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('nama_kabupaten', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('kode_propinsi', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('nama_propinsi', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('akreditasi_sekolah', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nilai_akreditasi', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('file_akreditasi', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tanggal_kadaluarsa', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('kepemilikan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}