<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ranking_Semester', 'doctrine');

/**
 * BaseRanking_Semester
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nomor_pendaftaran
 * @property integer $semester
 * @property string $jenis_kelas
 * @property integer $jumlah_siswa
 * @property float $indeks_mapel_un
 * @property integer $ranking_mapel_un
 * 
 * @method integer          getId()                Returns the current record's "id" value
 * @method integer          getNomorPendaftaran()  Returns the current record's "nomor_pendaftaran" value
 * @method integer          getSemester()          Returns the current record's "semester" value
 * @method string           getJenisKelas()        Returns the current record's "jenis_kelas" value
 * @method integer          getJumlahSiswa()       Returns the current record's "jumlah_siswa" value
 * @method float            getIndeksMapelUn()     Returns the current record's "indeks_mapel_un" value
 * @method integer          getRankingMapelUn()    Returns the current record's "ranking_mapel_un" value
 * @method Ranking_Semester setId()                Sets the current record's "id" value
 * @method Ranking_Semester setNomorPendaftaran()  Sets the current record's "nomor_pendaftaran" value
 * @method Ranking_Semester setSemester()          Sets the current record's "semester" value
 * @method Ranking_Semester setJenisKelas()        Sets the current record's "jenis_kelas" value
 * @method Ranking_Semester setJumlahSiswa()       Sets the current record's "jumlah_siswa" value
 * @method Ranking_Semester setIndeksMapelUn()     Sets the current record's "indeks_mapel_un" value
 * @method Ranking_Semester setRankingMapelUn()    Sets the current record's "ranking_mapel_un" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRanking_Semester extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Ranking_Semester');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nomor_pendaftaran', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('semester', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('jenis_kelas', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('jumlah_siswa', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('indeks_mapel_un', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ranking_mapel_un', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}