<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Nilai', 'doctrine');

/**
 * BaseData_Nilai
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nomor_pendaftaran
 * @property integer $id_kelas
 * @property integer $semester
 * @property string $kode_mata_pelajaran
 * @property float $nama_mata_pelajaran_kesetaraan
 * @property float $nilai_skala_4
 * @property float $nilai_skala_100
 * @property integer $tahun_kur
 * @property string $basis
 * @property float $unit
 * @property float $remedial_4
 * @property float $remedial_100
 * @property float $kkm
 * 
 * @method integer    getId()                             Returns the current record's "id" value
 * @method integer    getNomorPendaftaran()               Returns the current record's "nomor_pendaftaran" value
 * @method integer    getIdKelas()                        Returns the current record's "id_kelas" value
 * @method integer    getSemester()                       Returns the current record's "semester" value
 * @method string     getKodeMataPelajaran()              Returns the current record's "kode_mata_pelajaran" value
 * @method float      getNamaMataPelajaranKesetaraan()    Returns the current record's "nama_mata_pelajaran_kesetaraan" value
 * @method float      getNilaiSkala4()                    Returns the current record's "nilai_skala_4" value
 * @method float      getNilaiSkala100()                  Returns the current record's "nilai_skala_100" value
 * @method integer    getTahunKur()                       Returns the current record's "tahun_kur" value
 * @method string     getBasis()                          Returns the current record's "basis" value
 * @method float      getUnit()                           Returns the current record's "unit" value
 * @method float      getRemedial4()                      Returns the current record's "remedial_4" value
 * @method float      getRemedial100()                    Returns the current record's "remedial_100" value
 * @method float      getKkm()                            Returns the current record's "kkm" value
 * @method Data_Nilai setId()                             Sets the current record's "id" value
 * @method Data_Nilai setNomorPendaftaran()               Sets the current record's "nomor_pendaftaran" value
 * @method Data_Nilai setIdKelas()                        Sets the current record's "id_kelas" value
 * @method Data_Nilai setSemester()                       Sets the current record's "semester" value
 * @method Data_Nilai setKodeMataPelajaran()              Sets the current record's "kode_mata_pelajaran" value
 * @method Data_Nilai setNamaMataPelajaranKesetaraan()    Sets the current record's "nama_mata_pelajaran_kesetaraan" value
 * @method Data_Nilai setNilaiSkala4()                    Sets the current record's "nilai_skala_4" value
 * @method Data_Nilai setNilaiSkala100()                  Sets the current record's "nilai_skala_100" value
 * @method Data_Nilai setTahunKur()                       Sets the current record's "tahun_kur" value
 * @method Data_Nilai setBasis()                          Sets the current record's "basis" value
 * @method Data_Nilai setUnit()                           Sets the current record's "unit" value
 * @method Data_Nilai setRemedial4()                      Sets the current record's "remedial_4" value
 * @method Data_Nilai setRemedial100()                    Sets the current record's "remedial_100" value
 * @method Data_Nilai setKkm()                            Sets the current record's "kkm" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Nilai extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Nilai');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nomor_pendaftaran', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_kelas', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('semester', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('kode_mata_pelajaran', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nama_mata_pelajaran_kesetaraan', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nilai_skala_4', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nilai_skala_100', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tahun_kur', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('basis', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('unit', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('remedial_4', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('remedial_100', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('kkm', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}