<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Data_Kelas', 'doctrine');

/**
 * BaseData_Kelas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_kelas
 * @property integer $tahun_kelas_diselenggarakan
 * @property integer $tingkat
 * @property string $nama_kelas
 * @property string $kode_jenis_kelas
 * @property integer $id_jurusan
 * 
 * @method integer    getId()                          Returns the current record's "id" value
 * @method integer    getIdKelas()                     Returns the current record's "id_kelas" value
 * @method integer    getTahunKelasDiselenggarakan()   Returns the current record's "tahun_kelas_diselenggarakan" value
 * @method integer    getTingkat()                     Returns the current record's "tingkat" value
 * @method string     getNamaKelas()                   Returns the current record's "nama_kelas" value
 * @method string     getKodeJenisKelas()              Returns the current record's "kode_jenis_kelas" value
 * @method integer    getIdJurusan()                   Returns the current record's "id_jurusan" value
 * @method Data_Kelas setId()                          Sets the current record's "id" value
 * @method Data_Kelas setIdKelas()                     Sets the current record's "id_kelas" value
 * @method Data_Kelas setTahunKelasDiselenggarakan()   Sets the current record's "tahun_kelas_diselenggarakan" value
 * @method Data_Kelas setTingkat()                     Sets the current record's "tingkat" value
 * @method Data_Kelas setNamaKelas()                   Sets the current record's "nama_kelas" value
 * @method Data_Kelas setKodeJenisKelas()              Sets the current record's "kode_jenis_kelas" value
 * @method Data_Kelas setIdJurusan()                   Sets the current record's "id_jurusan" value
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseData_Kelas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Data_Kelas');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_kelas', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('tahun_kelas_diselenggarakan', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('tingkat', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('nama_kelas', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('kode_jenis_kelas', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_jurusan', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}