# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Starter Project symfony 1.4 Admin LTE
    description:  Starter Project symfony 1.4 Admin LTE
    keywords:     Starter Project symfony 1.4 Admin LTE
    language:     id
    robots:       index, follow

  stylesheets:    
                  - /bootstrap/css/bootstrap.min.css
                  - /font-awesome-4.5.0/css/font-awesome.min.css
                  - /ionicons-2.0.1/css/ionicons.min.css
                  - /css/AdminLTE.min.css
                  - /css/skins/skin-blue-light.min.css
                  - /js/plugins/iCheck/flat/blue.css
                  - /js/plugins/jvectormap/jquery-jvectormap-1.2.2.css
                  - /js/plugins/datepicker/datepicker3.css
                  - /js/plugins/daterangepicker/daterangepicker-bs3.css
                  - /js/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css

  javascripts:    
                  - /js/plugins/jQuery/jQuery-2.1.4.min.js
                  - /jquery-ui-1.11.4/jquery-ui.min.js
                  - /js/resolve-conflict.js
                  - /bootstrap/js/bootstrap.min.js
                  - /js/raphael/2.1.0/raphael-min.js
                  - /js/plugins/sparkline/jquery.sparkline.min.js
                  - /js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js
                  - /js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js
                  - /js/plugins/knob/jquery.knob.js
                  - /js/moment.js/2.10.2/moment.min.js
                  - /js/plugins/daterangepicker/daterangepicker.js
                  - /js/plugins/datepicker/bootstrap-datepicker.js
                  - /js/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js
                  - /js/plugins/slimScroll/jquery.slimscroll.min.js
                  - /js/plugins/fastclick/fastclick.min.js
                  - /js/app.min.js
                  - /js/pages/dashboard.js
                  - /js/demo.js

  has_layout:     true
  layout:         layout
