<?php

/**
 * Data_SekolahTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Data_SekolahTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Data_SekolahTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Data_Sekolah');
    }
}