<?php

/**
 * Data_Status_TambahanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Data_Status_TambahanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Data_Status_TambahanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Data_Status_Tambahan');
    }
}