<?php

/**
 * Data_Perubahan_NPSNTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Data_Perubahan_NPSNTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Data_Perubahan_NPSNTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Data_Perubahan_NPSN');
    }
}