<?php

/**
 * Data_NilaiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Data_NilaiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Data_NilaiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Data_Nilai');
    }
}