<?php

/**
 * Data_Kelas_Siswa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Data_Kelas_Siswa extends BaseData_Kelas_Siswa
{
}
