<?php

/**
 * Data_SiswaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Data_SiswaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Data_SiswaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Data_Siswa');
    }
}