<?php

/**
 * Data_PilihanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Data_PilihanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Data_PilihanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Data_Pilihan');
    }
}