<?php

/**
 * Data_Statistik_PenghasilanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Data_Statistik_PenghasilanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Data_Statistik_PenghasilanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Data_Statistik_Penghasilan');
    }
}