<?php

/**
 * Data_PrestasiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Data_PrestasiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Data_PrestasiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Data_Prestasi');
    }
}