<?php

/**
 * Data_Nilai_Mapel_UN_Kolom_SMK_Skala100Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Data_Nilai_Mapel_UN_Kolom_SMK_Skala100Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Data_Nilai_Mapel_UN_Kolom_SMK_Skala100Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Data_Nilai_Mapel_UN_Kolom_SMK_Skala100');
    }
}