<?php

/**
 * Data_Karya_PortofolioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Data_Karya_PortofolioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Data_Karya_PortofolioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Data_Karya_Portofolio');
    }
}