<?php

/**
 * Data_KelasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Data_KelasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Data_KelasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Data_Kelas');
    }
}