<?php

/**
 * Data_Nilai_Mapel_UN_Kolom_SMA_MA_Skala100
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Data_Nilai_Mapel_UN_Kolom_SMA_MA_Skala100 extends BaseData_Nilai_Mapel_UN_Kolom_SMA_MA_Skala100
{
}
