<?php

/**
 * Data_JurusanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Data_JurusanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Data_JurusanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Data_Jurusan');
    }
}