<?php

/**
 * Data_Nilai_Status_Tambahan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Data_Nilai_Status_Tambahan extends BaseData_Nilai_Status_Tambahan
{
}
