<?php

/**
 * Ranking_AkumulasiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ranking_AkumulasiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Ranking_AkumulasiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ranking_Akumulasi');
    }
}