<?php

/**
 * Ranking_SemesterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ranking_SemesterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Ranking_SemesterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ranking_Semester');
    }
}