<?php

/**
 * Ref_Jenis_PortofolioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ref_Jenis_PortofolioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Ref_Jenis_PortofolioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ref_Jenis_Portofolio');
    }
}