<?php

/**
 * Ref_Mata_Pelajaran_Jurusan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    snmptn_ppkb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ref_Mata_Pelajaran_Jurusan extends BaseRef_Mata_Pelajaran_Jurusan
{
}
