<?php

/**
 * Ref_Jenis_KelaminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ref_Jenis_KelaminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Ref_Jenis_KelaminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ref_Jenis_Kelamin');
    }
}