<?php

/**
 * Ref_Status_TambahanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ref_Status_TambahanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Ref_Status_TambahanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ref_Status_Tambahan');
    }
}