<?php

/**
 * Ref_JurusanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ref_JurusanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Ref_JurusanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ref_Jurusan');
    }
}