<?php

/**
 * Ref_Mata_PelajaranTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ref_Mata_PelajaranTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Ref_Mata_PelajaranTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ref_Mata_Pelajaran');
    }
}